export const works = [
  { id: 1, year: 2019, techUsed: ['React', 'Redux', 'node.js', 'google firebase'], myRole: 'Co-Founder, Web Developer', title: 'Leesa', description: 'Officia sit nisi tempor aute fugiat excepteur esse proident.', image: 'https://images.unsplash.com/photo-1590507155885-45f4b30d848a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60' },
  { id: 2, year: 2020, techUsed: ['Shopify, liquid, HTML, scss'], myRole: 'Web Developer, Project Manager', title: 'Barbiz', description: 'Officia sit nisi tempor aute fugiat excepteur esse proident.', image: 'https://images.unsplash.com/photo-1590507155885-45f4b30d848a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60' },
  { id: 3, year: 2018, techUsed: ['Shopify, liquid, HTML, scss'], myRole: 'Web Developer, Project Manager', title: 'Zuman Jewelry', description: 'Officia sit nisi tempor aute fugiat excepteur esse proident.', image: 'https://images.unsplash.com/photo-1590507155885-45f4b30d848a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60' },
]

export const projects = [
  { id: 1, year: 2020, techUsed: ['Ruby on Rails', 'PostgreSQL', 'scss', 'Javascript'], myRole: 'Web Developer', title: 'Camerent', description: 'Officia sit nisi tempor aute fugiat excepteur esse proident.', image: 'https://images.unsplash.com/photo-1590507155885-45f4b30d848a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60' },
  { id: 2, year: 2020, techUsed: ['Ruby on Rails', 'PostgreSQL', 'scss', 'Javascript'], myRole: 'Web Developer', title: 'Crank', description: 'Officia sit nisi tempor aute fugiat excepteur esse proident.', image: 'https://images.unsplash.com/photo-1590507155885-45f4b30d848a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60' },
  { id: 3, year: 2020, techUsed: ['React', 'node.js', 'mongoDB', 'express.js'], myRole: 'Web Developer', title: 'Pytagoras', description: 'Officia sit nisi tempor aute fugiat excepteur esse proident.', image: 'https://images.unsplash.com/photo-1590507155885-45f4b30d848a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60' },
]